
version: '3.3'


services:
  redis:
    image: "redis:alpine"
    restart: always

  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: fotokarpov/analitik:v1.0
    restart: always
    volumes:
      - static:/code/static/
      - media:/code/media/
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    entrypoint: /code/start.sh
  
  # celery:
  #   image: "celery:5.1.2"
  #   restart: always
  #   command: celery -A banking_analytics worker -l info
  #   volumes:
  #     - celery:/code/
  #   depends_on:
  #     - web
  #     - redis
  
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - web


volumes:
  postgres_data:
  static:
  media:
  # celery:
