
version: '3.3'


services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: fotokarpov/foodgram:v1.0
    restart: always
    volumes:
      - static:/code/static/
      - media:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env


volumes:
  postgres_data:
  static:
  media:
