# Generated by Django 3.2.7 on 2021-12-04 19:28

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок новости')),
                ('text', models.CharField(max_length=2000, verbose_name='Текст новости')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публикуемая новость ?')),
                ('data_news', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания новости')),
                ('update_news', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения новости')),
                ('image', models.ImageField(upload_to=apps.news.models.News.get_image_path, verbose_name='Фото для новости')),
            ],
            options={
                'ordering': ['-update_news'],
            },
        ),
    ]
