# Generated by Django 3.2.7 on 2021-12-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-update_news'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
