# Generated by Django 3.2.7 on 2021-10-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='char_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Символьный код валюты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='num_code',
            field=models.PositiveSmallIntegerField(help_text='Дайте валюте цировой код', unique=True, verbose_name='Цировой код валюты'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(help_text='Дата установки курса', verbose_name='Курс валюты на дату'),
        ),
    ]
