# Generated by Django 3.2.7 on 2021-10-09 21:16

from django.conf import settings
from django.db import migrations


def update_site_name(apps, schema_editor):
    SiteModel = apps.get_model('sites', 'Site')
    domain = 'analitik.online'

    SiteModel.objects.update_or_create(
        pk=settings.SITE_ID,
        defaults={'domain': domain,
                  'name': domain}
    )


class Migration(migrations.Migration):

    dependencies = [
        # Make sure the dependency that was here by default is also included here
        # Required to reference `sites` in `apps.get_model()`
        ('currency', '0002_auto_20211006_1435'),
        ('sites', '0002_alter_domain_unique'),
        
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]
