# Generated by Django 3.2.7 on 2022-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, help_text='Определяет, подтвердил ли пользователь свой email.Перешел ли пользователь по ссылке, отправленной в письме.', verbose_name='active'),
        ),
    ]
