# Generated by Django 3.2.7 on 2021-10-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=1000, verbose_name='Официальное польное наименование')),
                ('short_name', models.CharField(max_length=500, verbose_name='Официальное сокращенное наименование')),
                ('bic', models.CharField(max_length=9, verbose_name='Код BIC кредитной организации')),
                ('reg_date', models.DateField(verbose_name='Дата регистрации кредитной организации в ЦБ')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование кредитной организации')),
                ('ogrn', models.CharField(max_length=256, verbose_name='Основной государственный регистрационный номер')),
                ('reg_number', models.CharField(max_length=256, verbose_name='Регистрационный номер кредитной организации в ЦБ')),
                ('internal_number', models.CharField(max_length=256, verbose_name='Внутренний номер кредитной организации в ЦБ')),
                ('cregnr', models.CharField(blank=True, max_length=256, verbose_name='Дополнительный регистрационный номер в ЦБ')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название региона')),
                ('code', models.PositiveSmallIntegerField(verbose_name='Код региона')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
