# Generated by Django 3.2.7 on 2021-10-12 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название региона')),
                ('code', models.PositiveSmallIntegerField(verbose_name='Код региона')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='bank',
            name='sort_name',
        ),
        migrations.AddField(
            model_name='bank',
            name='bic',
            field=models.CharField(default=django.utils.timezone.now, max_length=9, verbose_name='Код BIC кредитной организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='internal_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Внутренний номер кредитной организации в ЦБ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(default=datetime.datetime(2021, 10, 12, 19, 1, 12, 598821, tzinfo=utc), max_length=256, verbose_name='Наименование кредитной организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='ogrn',
            field=models.CharField(default=1, max_length=256, verbose_name='Основной государственный регистрационный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='reg_number',
            field=models.CharField(default=1, max_length=256, verbose_name='Регистрационный номер кредитной организации в ЦБ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации кредитной организации в ЦБ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='short_name',
            field=models.CharField(default=1, max_length=500, verbose_name='Официальное сокращенное наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='long_name',
            field=models.CharField(max_length=1000, verbose_name='Официальное польное наименование'),
        ),
    ]
