# Generated by Django 3.2.7 on 2022-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indCode', models.CharField(max_length=30, unique=True, verbose_name='Номер счета')),
                ('name', models.CharField(max_length=1000, verbose_name='Название счетов баланса')),
                ('indType', models.CharField(max_length=30, verbose_name='Код счета')),
                ('indChapter', models.CharField(max_length=30, verbose_name='Код раздела')),
            ],
            options={
                'ordering': ['indCode'],
            },
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Код региона'),
        ),
    ]
