# Generated by Django 3.2.7 on 2021-10-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20211012_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='registration_date',
            new_name='reg_date',
        ),
        migrations.AddField(
            model_name='bank',
            name='cregnr',
            field=models.CharField(blank=True, max_length=256, verbose_name='Дополнительный регистрационный номер в ЦБ'),
        ),
    ]
