# Generated by Django 3.2.7 on 2022-03-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20220105_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanksBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Балансовые данные на дату')),
                ('rub_balance', models.IntegerField(verbose_name='Остаток в рублях на дату')),
                ('cur_balance', models.IntegerField(verbose_name='Остаток в валюте на дату')),
                ('itog_balance', models.IntegerField(verbose_name='Итоговый остаток в рублях и в валюте на дату')),
                ('ora', models.IntegerField(verbose_name='Оборот в рублях по дебиту')),
                ('ova', models.IntegerField(verbose_name='Оборот в валюте по дебиту')),
                ('oitga', models.IntegerField(verbose_name='Итоговый оборот в рублях и в валюте по дебету')),
                ('orp', models.IntegerField(verbose_name='Оборот в рублях по кредиту')),
                ('ovp', models.IntegerField(verbose_name='Оборот в валюте по кредиту')),
                ('oitgp', models.IntegerField(verbose_name='Итоговый оборот в рублях и в валюте по кредиту')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank', verbose_name='Банк')),
                ('indCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.balanceaccount', verbose_name='Номер счета')),
            ],
            options={
                'verbose_name': 'Остатки на дату и обороты за предыдущий период',
                'verbose_name_plural': 'Остатки на дату и обороты за предыдущий период',
                'ordering': ['-date'],
            },
        ),
    ]
